# API Gamivo "postman"
###
GET http://localhost:3000/account-data

###
GET http://localhost:3000/calculate-final-price

###
GET http://localhost:3000/offer-list?offset=400&limit=1000
###
POST http://localhost:3000/create-offer
Content-Type: application/json

{
    "product": "",
    "wholesale_mode": "",
    "seller_price": "",
    "tier_one_seller_price": "", 
    "tier_two_seller_price": "",
    "status": "",
    "keys": "",
    "is_preorder": ""
}

###
GET http://localhost:3000/search/offer/2499645

###
GET http://localhost:3000/compare/all

###
GET http://localhost:3000/compare/141433


###
# GET http://localhost:3000/compare-all-games