# API Gamivo "postman"
###
GET http://localhost:3000/api/accounts/accountData

###
GET http://localhost:3000/api/accounts/calculateFinalPrice

### Offerlist normal
GET http://localhost:3000/api/offers/offersList?offset=4400&limit=100

### Offerlist com loop p descobrir jogos impossíveis
GET http://localhost:3000/api/offers/offersList?ids=74797,78621,26374

###
POST http://localhost:3000/api/offers/createOffer
Content-Type: application/json

{
    "product": "",
    "wholesale_mode": "0",
    "seller_price": 15,
    "tier_one_seller_price": "",
    "tier_two_seller_price": "",
    "status": 1,
    "keys": 3,
    "is_preorder": false
}

###
GET http://localhost:3000/api/offers/search/2499645

###
GET http://localhost:3000/api/products/productsList

###
GET http://localhost:3000/api/products/productIds

### O número do meio que é o jogo impossível
    #"myProductIds": [31004, 1622240, 142477]
POST http://localhost:3000/api/products/compareAll
Content-Type: application/json

{
    "myProductIds": [31004, 1622240, 142477]
}

### Dá p descobrir o nome do jogo enviando o id para essa rota
GET http://localhost:3000/api/products/compareById/46535

###
GET http://localhost:3000/api/jobs/attPrices

###
GET http://localhost:3000/api/sheets/catchFromSheet
# Content-Type: application/json
# {
#   "filePath": "./BestbuyTrue.xlsx",
#   "sheetName": "Venda-Chave-Troca"
# }

###
GET http://localhost:3000/api/products/productsBySlug
Content-Type: application/json

{
    "gameName": "CRYPTARK EN Global"
}